k=0:1000
xk1<-4*sin((pi*(k-2))/3.0)
t1<-fft(xk1)
plot(t1,type="h",xlab="K",ylab="DFT of 3a(1)")
mag1=abs(t1)
arg1=Arg(t1)
plot(arg1,type="h",xlab="K",ylab="phase spectra of 3a(1)")
plot(mag1,tpye="h",xlab="K",ylab="magnitude of 3a(1)")

xk2<-cos((2*pi*k)/3.0)+sin((2*pi*k)/5.0)
t2<-fft(xk2)
plot(t2,type="h",xlab="K",ylab="DFT of 3a(2)")
mag2=abs(t2)
arg2=Arg(t2)
plot(arg2,type="h",xlab="K",ylab="phase spectra of 3a(2)")
plot(mag2,tpye="h",,xlab="K",ylab="magnitude of of 3a(2)")

xk3<-cos((2*pi*k)/3.0)*sin((2*pi*k)/5.0)
t3<-fft(xk3)
plot(t3,type="h",xlab="K",ylab="DFT of 3a(3)")
mag3=abs(t3)
arg3=Arg(t3)
plot(arg3,type="h",xlab="K",ylab="phase spectra of 3a(3)")
plot(mag3,tpye="h",xlab="K",ylab="magnitude spectra of 3a(3)")